### ISSUE TITLE
LGTM画像内のフォントのカスタマイズ機能の実装

### ISSUE THREAD

**Issue by kazzyfrog** [lgtm-factory/lgtm-factory#108]
## 概要

上記より、タスクを切り分けました。

- #81 

LGTM画像内の、フォントのカスタマイズ機能を実装します！

具体的には、Google Fonts の Developer API？からフォントデータを取得する実装になるかな、と思いますが、
まだ調査できてないので、イシューのみ立てておきます👍

## 目的

LGTM画像の、フォントを柔軟に変更できるようにすることで、デザインの自由度を高めるため

## 提案内容

フォントデータを柔軟に変更できるようにする

## タスク

- [ ] 実装についての調査
- [ ] フォントのカスタマイズ機能を実装

**Comment by kagomen** [comment]
こちらの記事がとても詳しく、参考になりました！
https://trpfrog.net/blog/google-fonts-on-satori

**Comment by kazzyfrog** [comment]
ありがとうございます！！👍
チェックします！
