### ISSUE TITLE
CONTRIBUTING.mdに、issue ベースの開発の流れ（手順書）を記載する

### ISSUE THREAD

**Issue by kagomen** [lgtm-factory/lgtm-factory#11]
## 概要

CONTRIBUTING.mdに、issue ベースの開発の流れ（手順書）を記載する。

## 参考

- [GitHubを使ったissueベースワークフロー](https://qiita.com/nabion/items/bd6e950759c8be77468b)
- [［GitHub］一人開発でもissueベース/セルフプルリクエストを使って開発する](https://qiita.com/braveryk7/items/5208263cd06a8878f0c2)

## タスク

- [ ] docs/CONTRIBUTING.mdに、issue ベースの開発の流れ（手順書）を記載する。

**Comment by hamanyann** [comment]
最終ゴールがイメージできなかったのでfirst-contributions-jaのcontributionsも参考にしながら書いてみます。

**Comment by kagomen** [comment]
@kazzyfrog 
こちら、「 #16 と #25 を参考に作業してくださいー」みたいなことを書くだけでも良いでしょうか？👀

**Comment by kazzyfrog** [comment]
こんな感じを貼り付けるのは、どうでしょうか？


---
0. はじめに
- リモートリポジトリを、ローカルにクローンしていることを確認して下さい
- 最新のリモートリポジトリの状態を反映させるため、以下のコマンドを実行します
  ```zsh
  git pull
  ```

1. main ブランチから、作業用ブランチを作成 & 移動する。
   ```
   git switch -c feature/add-xxx
   ```
2. 実際に作業を行い、変更をコミットする。
   ```
   git add .
   git commit -m "xxxの実装"
   ```
3. 変更をリポートリポジトリに、プッシュする
   ```
   git push origin HEAD
   ```
4. プルリクエストを作成する
5. 作業用ブランチから、main ブランチに戻る
   ```
   git switch main
   ```
6. main ブランチを最新の状態に更新する
   ```
   git pull origin main
   ```
7. 作業し終わったブランチを削除する
   ```
   git branch -d feature/add-xxx
   ```

---

**Comment by kagomen** [comment]
@kazzyfrog 

あら・・・！結局書かせてしまい、すみません🙏💦💦
こちらを参考に、CONTRIBUTING.mdのフォーマットに合わせてコマンドの内容をちょっと変更して、PRします！！
ありがとうございますー！🙇✨
