### ISSUE TITLE
ロゴと背景画像をassetsに配置

### ISSUE THREAD

**Issue by kagomen** [lgtm-factory/lgtm-factory#124]
## 概要
サイト内で使用する素材をassetsディレクトリに配置します

**Comment by kazzyfrog** [comment]
画像配置用のディレクトリとして、
現状`public`ディレクトリもあるので、どっちかにまとめた方がいいかもですね！

**Comment by kagomen** [comment]
@kazzyfrog 
そういえば……！
ちょっと調査します……！！
