### ISSUE TITLE
CONTRIBUTING.mdに、当プロジェクトにおけるコミットメッセージ規約を記載する

### ISSUE THREAD

**Issue by kagomen** [lgtm-factory/lgtm-factory#13]
## 概要

CONTRIBUTING.mdに、当プロジェクトにおけるコミットメッセージ規約を記載する。

## 参考

- [Gitのコミットメッセージの書き方](https://qiita.com/itosho/items/9565c6ad2ffc24c09364)
- [良いコミットメッセージのルールメモ](https://zenn.dev/shotaro/articles/2022-04-20-0000)

## タスク

- [ ] docs/CONTRIBUTING.mdに、当プロジェクトにおけるコミットメッセージ規約を記載する。

**Comment by siso001** [comment]
* https://zenn.dev/itosho/articles/git-commit-message-2023

**Comment by siso001** [comment]
参考資料そのままですがファイルに記述しました
共同開発の経験がないため、修正した方がいい部分などがあればお願いします！
