### ISSUE TITLE
Metadataの設定

### ISSUE THREAD

**Issue by kagomen** [lgtm-factory/lgtm-factory#141]
## 概要
Metadataの設定

## 目的
サイトのタイトルや説明を表示させるため

## タスク

- [ ] layout.tsxにMetadataを設定？

## その他
とりあえず静的なメタデータだけで良いでしょうか……？

## 参考
- https://nextjs.org/docs/app/building-your-application/optimizing/metadata
- https://nextjs.org/learn/dashboard-app/adding-metadata

**Comment by kazzyfrog** [comment]
> とりあえず静的なメタデータだけで良いでしょうか……？

良いと思います👍
