### ISSUE TITLE
CODE_OF_CONDUCT.mdの作成

### ISSUE THREAD

**Issue by kazzyfrog** [lgtm-factory/lgtm-factory#15]
## 概要
オープンソースのプロジェクトに必要な、
行動規範をテンプレートに沿って、作成します！

参加者は、どのように振る舞うかといったルールなどを記載する、ドキュメントです！

**Comment by kazzyfrog** [comment]
@soraOrange 
こちらのイシュー取り組まれますか？

自分やろうと思ってましたが、もしよかったら譲りますよ！👍
（Assigneesに、追加に追加されていたので！）

**Comment by soraOrange** [comment]
@kazzyfrog 
すいません、練習で触っておりました🙇
失礼いたしました...

**Comment by kazzyfrog** [comment]
了解ですー！！
全然大丈夫ですよ！w
