### ISSUE TITLE
画像の編集画面（モーダル）を作成

### ISSUE THREAD

**Issue by kazzyfrog** [lgtm-factory/lgtm-factory#150]
## 概要

右側に開く、編集画面ダイアログ（モーダル）を作成します。
そこに、下記を配置します
- 作成済みのコピーボタンと、DLボタン
- inputDataの入力欄
- （可能なら、Xシェアボタン）

## タスク

- [x] インストールされている、shadcn/uiの`sheet`を使用して実装

**Comment by siso001** [comment]
divのheightを手書きで変更すると0pxになるが、別のところからコピペしたりvscodeの予測変換で変更すると、何故か正しく適応されるバグで少し困りました

**Comment by kazzyfrog** [comment]
@siso001 

もしかしたら、バグではなくて、heightで使える値が制限されているからかも？です！👀
https://tailwindcss.com/docs/height

もし制限を無視したかったら`h-[17px]`のようにも書けますよ👍

**Comment by siso001** [comment]
ありがとうございます！試してみます🙏

**Comment by siso001** [comment]
sheetのwidthをw-[〇〇px]のように設定しようとしましたが、380px~辺りでどうしても上限に引っかかります！
xシェアボタン以外の要素は配置できたので、シェアボタンを実装してから調査します

**Comment by siso001** [comment]
Xシェアボタン参考資料
- https://help.studio.design/ja/articles/2677605-x-twitter-%E3%82%B7%E3%82%A7%E3%82%A2%E3%83%9C%E3%82%BF%E3%83%B3%E3%81%AE%E8%A8%AD%E7%BD%AE%E6%96%B9%E6%B3%95

**Comment by kazzyfrog** [comment]
Xシェアボタンは、現状READMEにあるものや、
下記にて、メタデータファイル内にURLを作成したので、参考にしてみてください👍
- #154

**Comment by kagomen** [comment]
@siso001 

実際に動かしてないので微妙ですが、
以下のcomponents/shadcn-ui/sheet.tsxのソースコードの、`sm:max-w-sm`や`w-3/4`クラスあたりが原因かも……？

```ts
const sheetVariants = cva(
  "fixed z-50 gap-4 bg-background p-6 shadow-lg transition ease-in-out data-[state=open]:animate-in data-[state=closed]:animate-out data-[state=closed]:duration-300 data-[state=open]:duration-500",
  {
    variants: {
      side: {
        top: "inset-x-0 top-0 border-b data-[state=closed]:slide-out-to-top data-[state=open]:slide-in-from-top",
        bottom:
          "inset-x-0 bottom-0 border-t data-[state=closed]:slide-out-to-bottom data-[state=open]:slide-in-from-bottom",
        left: "inset-y-0 left-0 h-full w-3/4 border-r data-[state=closed]:slide-out-to-left data-[state=open]:slide-in-from-left sm:max-w-sm",
        right:
          "inset-y-0 right-0 h-full w-3/4  border-l data-[state=closed]:slide-out-to-right data-[state=open]:slide-in-from-right sm:max-w-sm",
      },
    },
    defaultVariants: {
      side: "right",
    },
  },
);
```

sheet.tsxの内容を変更するか、
レイアウト的に微妙だったら、スマホのサイズのみ`side="bottom"`にしても良いかも？👀
もしくは、別イシューとしてレスポンシブ対応を切り出しても🙆

**Comment by siso001** [comment]
@kazzyfrog 了解です！ありがとうございます

**Comment by siso001** [comment]
@kagomen sm:max-w-smが原因でした！感謝！

chatgptに聞いた
sm:max-w-smは、Tailwind CSSで使用されるクラス名で、画面サイズに応じた最大幅（max-width）を指定するためのものです。これを詳しく説明すると、以下のようになります：

    sm: は、Tailwind CSSのブレークポイントの一つで、「小さな」デバイスに適用されるスタイルを指定します。通常、これは640px以上の幅の画面（小さなスクリーン）に適用されます。
    max-w-sm は、最大幅を指定するユーティリティクラスです。smは「small」を意味し、指定された要素の最大幅を24rem（通常は384px）に設定します。

したがって、sm:max-w-smは、画面幅が640px以上の場合に、その要素の最大幅を384pxに制限することを意味します。これにより、レスポンシブデザインが容易になり、小さなスクリーンでは要素が適切な幅に調整されます。


figmaのデザインとはズレてますが、特別おかしいレイアウトではないので一旦これでプルリク送ろうと思います！
細かいレイアウトは色々考えてから別イシューで

**Comment by kagomen** [comment]
@siso001 

> figmaのデザインとはズレてますが、特別おかしいレイアウトではないので一旦これでプルリク送ろうと思います！
細かいレイアウトは色々考えてから別イシューで

了解です！🌟

**Comment by kazzyfrog** [comment]
@siso001 
もし迷った点などがあれば、
作業の途中でも、プルリクエストを作成して大丈夫ですよー👍
