### ISSUE TITLE
TOPページの実装

### ISSUE THREAD

**Issue by kazzyfrog** [lgtm-factory/lgtm-factory#166]
## 概要

現在、TOPページの各コンポーネント、編集用モーダルが、別イシューにて作業されています！
上記が完了したら、これらを連携させ、TOPページを完成させます。

## タスク

- [x] メインセクションの実装
- [ ] 編集用モーダルの実装＆連携
- [ ] TOPページに、GitHubからコントリビュートできる「cta セクション（もしくは、contribute-offer セクション）」の作成

その他チェック：

- [x] 不要なコメントアウト、ダミーデータの削除

**Comment by siso001** [comment]
TOPページの処理について https://github.com/lgtm-factory/lgtm-factory/discussions/99

**Comment by kagomen** [comment]
#167 にて、マージ済みのPRにレビューしてしまったので、こちらのイシューでレビューしたCSSの部分もリファクタリングできれば、と思います！

以下、修正希望箇所です🫶
https://github.com/lgtm-factory/lgtm-factory/pull/167#pullrequestreview-2274227338

**Comment by kagomen** [comment]
ちょっと変更点多すぎてレビューが大変になると思うので、イシュー分割します！（すでに大変かも……😭すみません💦）

**Comment by kagomen** [comment]
## メモ：引き継ぎタスク

- [ ] `EditArea`コンポーネント（モーダルの編集部分）の機能実装
- [ ] CTAセクションの作成
- [ ] `ImageInfoModal`コンポーネント（モーダル）の、ボタンの色や背景の色、オーバーレイの色などをサイトイメージに合わせて調整する
- [ ] baseUrlの環境による出し分け
  - 出し分けをしてないため、現在開発環境ではDLボタンが効きません
