### ISSUE TITLE
TOPページのLGTM画像リストが表示されていない調査と修正

### ISSUE THREAD

**Issue by kazzyfrog** [lgtm-factory/lgtm-factory#169]
## 概要
現状、TOPページのLGTM画像リストが、正しく表示されていません。
（ローカルでは、表示できていることを確認しました）

これに関して、以下を調査し、修正します
- Imageコンポーネントや、Next.jsによって設定される、画像URLの挙動
- ローカルと、本番での違いについても、調査

要は、
**URL、画像周りに原因がありそうなので、調査し修正します**！

## 再現手順
アクセス：
https://lgtm-factory.pages.dev/

## 修正しないとどう困るか

メインコンテンツが表示できない

## 原因

調査！

## 修正案

Must
- [x] 原因を特定し、TOPページに画像一覧を表示する

できたら、
- [ ] ローカルと、本番環境のベースURLを設定し、どの環境でも確認できるようにする #176
- [ ] URLや、画像との取り扱いについて、ドキュメントに記載する

**Comment by kagomen** [comment]
一応、こちら https://github.com/lgtm-factory/lgtm-factory/pull/163#issuecomment-2322818611 で話したように、`npm run preview`で表示させることは可能（なはず！）であることを共有しておきます！

**Comment by kagomen** [comment]
#170 にて調査中🕵️

**Comment by kagomen** [comment]
#166 にて、`next.config.mjs`を以下のように設定して、応急処置的に画像を表示するコミットをつみます！

```
const nextConfig = {
  images: {
    unoptimized: true,
  },
};
```

**Comment by kazzyfrog** [comment]
- https://github.com/lgtm-factory/lgtm-factory/discussions/170#discussioncomment-10508635

一旦バグは解消できた！
原因は、上記の、Imageコンポーネントの、最適化機能が対応していないことによる、不具合だった！
これをオプトアウトして、解決！

なので、一旦クローズします！
