### ISSUE TITLE
`ImageInfoModal`の編集部分の機能実装

### ISSUE THREAD

**Issue by kagomen** [lgtm-factory/lgtm-factory#173]
## 概要
`ImageInfoModal`の編集部分の機能実装

## 目的
`Input`に入力された値に応じて、LGTM画像を編集・表示する

## タスク

- [x] 画像のthemeに応じた、designInfoのデータを取得する
- [x] designInfoデータの中にある、editableFields（ ユーザーが編集可能なフィールド（複数可））を参照する
- [x] editableFieldsに応じた、ラベルでインプットフォームを表示する機能
- [x] 入力された値で、画像（URL）を生成する機能

**Comment by kazzyfrog** [comment]
https://github.com/lgtm-factory/lgtm-factory/blob/main/design-guide.md#5-1デザイン情報について

編集モーダルを開いたら、以下のような処理の流れになりそうですね！
- 画像のthemeに応じた、`designInfo`のデータを取得する
- `designInfo`データの中にある、`editableFields`（ ユーザーが編集可能なフィールド（複数可））を参照する
- editableFieldsに応じた、ラベルでインプットフォームを表示する
- 入力された値で、画像（URL）を生成する：例）`/api/v1/lgtm-images?theme=abc&emoji=🫠🫠&text=LGTM`

**Comment by siso001** [comment]
@kazzyfrog ありがとうございます！順番に実装してみます！

**Comment by siso001** [comment]
shadcn/uiとconformでinputを実装する(参考資料)
https://zenn.dev/coji/articles/conform-shadcn-ui-input

**Comment by siso001** [comment]
https://ui.shadcn.com/docs/components/form

**Comment by siso001** [comment]
**1. register**

register は、フォームフィールド（<input> など）を react-hook-form に登録するために使用されます。register を使うことで、フォームデータが react-hook-form によって追跡され、管理されるようになります。
``` ts
<Input {...register("name")} placeholder="Your name" />
```
上記のように使うと、name という名前の入力フィールドが react-hook-form によって管理され、ユーザーが入力したデータは自動的に保存されます。

**2. handleSubmit**

handleSubmit は、フォームが送信された際に呼び出される関数で、フォームデータを処理するためのコールバック関数を指定できます。この関数を使うことで、フォームの送信時にエラーチェックや処理を行います。

``` ts
<form onSubmit={handleSubmit((data) => console.log(data))}>
  <Button type="submit">Submit</Button>
</form>
```

ここで、フォームが送信されると、handleSubmit がデータを引数として渡し、フォームの内容をコンソールに表示します。

**3. watch**
watch は、指定したフィールドの値の変更をリアルタイムで監視するために使います。特定の入力フィールドの値が変わるたびに、その値を取得できます。
``` ts
const name = watch("name", "Default Name");
```
上記のように使用すると、name フィールドの現在の値を取得できます。第2引数に渡した "Default Name" は、name に何も入力されていない場合のデフォルト値です。

**Comment by siso001** [comment]
useFormについてchatgptに聞きながらなんとか動くようになりました
あとはtextの変更しか実装してないので、emoji,color,のデータを受け取るようにする！
