### ISSUE TITLE
`ImageInfoModal`コンポーネント内で使用されている色を、サイトイメージに合わせて調整する

### ISSUE THREAD

**Issue by kagomen** [lgtm-factory/lgtm-factory#175]
## 概要
`ImageInfoModal`コンポーネント（モーダル）の、ボタンの色や背景の色、オーバーレイの色などをサイトイメージに合わせて調整する

## 目的
- デザイン性の向上

## タスク

- [x] 仮のデザイン（ざっくりイメージ）作成
- [ ] 実装
    - [ ] 必要があれば、globals.cssのカラーをいじる
    - [ ] 必要があれば、components/shadcn-ui/sheet.tsxをいじる

## その他
機能に直接関係ないので、優先度を低めに設定しました！

**Comment by kazzyfrog** [comment]
とても雑で、細かいサイズは適当ですが、
こんな感じでプリントが貼ってある感じでデザインしてみました！

内容は、Googleの画像検索が、いいなと思って参考にしました！
（左側に、サイズの異なる画像が並んでいて、右側のモーダルに選択した画像が表示される！）

問題なければ、これに合わせて実装＆GitHubへの誘導モーダルも作成します👍

![Group 184](https://github.com/user-attachments/assets/6993c6a1-31e2-4602-a138-017b4213956e)

参考：
![スクリーンショット 2024-09-03 1 51 36 1](https://github.com/user-attachments/assets/fa047131-3664-4d6a-a8d0-97a4606ec0dc)
