### ISSUE TITLE
CTAセクションの作成

### ISSUE THREAD

**Issue by kagomen** [lgtm-factory/lgtm-factory#177]
## 概要
CTAセクションの作成

## タスク

- [ ] CTAセクションの作成

**Comment by kazzyfrog** [comment]
ざっくりイメージで、テキストとかすごく適当ですが、
現状、こんな感じで実装しようかと思ってます！
<img width="664" alt="スクリーンショット 2024-09-04 4 29 27" src="https://github.com/user-attachments/assets/7feb395c-b12b-4e72-a2fd-3899ad0ba6dc">

**Comment by kagomen** [comment]
メモのようなデザイン、すごく可愛いです！📝　LGTMにも合ってる😻

ただ、気になった点としては、機能としては「+ New LGTM ?」のボタンひとつで役割を賄えるなーということです！

また、現状のLGTMボタンがずっと右下に固定されてることで機能面で何か不都合がある、などがあれば変更しても良いと思うのですが・・・！

というのが、自分の意見ですー！
参考にしていただけたら幸いです🙏

**Comment by kazzyfrog** [comment]
Github上に遷移して、ドキュメントを読まなくても、
サイト上でざっくり概要を伝えたいなと思っている感じです👍

**Comment by kagomen** [comment]
GitHubにいきなりリンク飛ばすのは、たしかに急かもですね🤔
そしたら、「+ New LGTM 🐈‍⬛」（🐈‍⬛がGitHubアイコン）にしたら、その先のアクションが予測できそうです！

> 「+ New LGTMボタン」をクリックしたら、
モーダルが開いて簡潔な説明と、GitHubへのリンクを配置できるなら、それも良さそうだなと思ってます！

動きがあって、良さそう！ユーザーもちゃんと読んでくれそう！
ボタンクリックしたら、提案されているメモの形をしたモーダルが開くのはどうですか？👀
実装難しいかな・・・

**Comment by kazzyfrog** [comment]
> ボタンクリックしたら、提案されているメモの形をしたモーダルが開くのはどうですか？👀

めっちゃいいと思います！
ただ、実装的に、一旦CTAセクション配置するならパパッと簡単にできるかなーと思っている感じですかね！w

**Comment by kagomen** [comment]
> 実装的に、一旦CTAセクション配置するだけなら、明確でパパッと簡単にできるかなーと思っている

それだったら現状のままでも良いんじゃないかな・・・？というのが、自分の考えです！👍
ただこれは個人的な考えですので、しそさんの意見（あれば！）や、kazzyfrogさんの最終決定にお任せしますー！

**Comment by kazzyfrog** [comment]
であれば、
LGTM画像編集モーダル（`sheet`のデザイン）も、別イシューであるかと思うので、
それが完了したら、そのデザインに合わせてモーダルで実装しますよ👍

**Comment by kazzyfrog** [comment]
shadcn/uiの[Popover](https://ui.shadcn.com/docs/components/popover)で、
右下の青いバナーをクリックしたら、上部に下記のデザインを表示しようかと考えていますー

（こちらも、ざっくりのイメージで、テキストとかすごく適当です）

- 閉じるための×ボタンはどこかに配置する予定です
- あと、青いバナーのテキストも、GitHubアイコン＋「contributing」、「create Design」、、など、少し分かりやすくしたいなと思ってます！（現状だと、LGTM画像を取得できるボタンなのかな？と、迷いそうなので！）

<img width="571" alt="スクリーンショット 2024-09-06 2 54 50" src="https://github.com/user-attachments/assets/571e9983-43b4-488f-8a9a-da4302bd3a97">
