### ISSUE TITLE
もしイシューの練習が終わったら、クローズしてください👍

### ISSUE THREAD

**Issue by kazzyfrog** [lgtm-factory/lgtm-factory#27]
## 概要

練習用のイシューは、**もし使い終わったら**、クローズしていただけると助かります！

もちろん、しばらく置いておいて、色々いじったりしても、
再度イシューを、立て直したりしてもOKです！

**Comment by kazzyfrog** [comment]
<img width="1297" alt="スクリーンショット 2024-08-07 1 59 02" src="https://github.com/user-attachments/assets/a67df71d-0cdc-40ca-b4eb-1986c0180858">

**Comment by soraOrange** [comment]
@kazzyfrog 
Closeしました！

**Comment by kazzyfrog** [comment]
@soraOrange 
ありがとうございますー！

このイシューもクローズします！
