### ISSUE TITLE
.githubディレクトリと、docsディレクトリを統合する

### ISSUE THREAD

**Issue by kazzyfrog** [lgtm-factory/lgtm-factory#44]
## 概要

.githubディレクトリと、docsディレクトリは、
同じ役割なので、どちらかに統合します。
（優先度は低いです。）

- #28 

上記より引用
> 行動規範(CODE_OF_CONDUCT.md)のような、
GitHubの機能を拡張するファイルは、以下の場所に配置することができます：[参考](https://docs.github.com/ja/communities/setting-up-your-project-for-healthy-contributions/creating-a-default-community-health-file#about-default-community-health-files)
> - リポジトリのルート
> - .github フォルダー
> - docs フォルダー
> 
> 上記の場所に配置することで、
GitHubから、特別なファイルであることを認識されるというイメージです。
> 
> 今回は、.githubフォルダーを作成し、その中にファイルを作成しました。
ルートに配置するよりは、特別なファイルをフォルダーにまとめたほうがいいかな、と思った次第です！
> 
> もし、別イシューにて、docs フォルダーが作成された場合は、
後ほど別のイシューを立てて、docsか.githubのどちらかに、ファイルをまとめたいと思ってます！

 ## 目的

同じ役割の別名ディレクトリがあることによって、少しでも混乱する可能性を減らすため。

 ## 提案内容

上述した通り。

 ## タスク
 
 - [ ] どちらかを選択し、中身を片方に移行。もう片方を削除。

**Comment by siso001** [comment]
.github、docsフォルダーの違いについて生成aiに聞いてみた

GitHubのリポジトリでドキュメントを整理する際、docsフォルダと.githubフォルダの役割は異なります。

- **docsフォルダ**: プロジェクト全体に関連する一般的なドキュメント（例: APIガイド、チュートリアル、セットアップ手順など）を含めるのに適しています。GitHub Pagesを利用してリポジトリの静的ウェブサイトを公開する際も、docsフォルダがよく使われます。

- **.githubフォルダ**: コラボレーションに関連する設定ファイル（例: Issueテンプレート、Pull Requestテンプレート、CONTRIBUTING.md、CODEOWNERSなど）を配置するためのフォルダです。また、README.mdやCODE_OF_CONDUCT.mdなど、リポジトリ全体に適用されるポリシーやガイドラインもここに置かれることがあります。

どちらに統一すべきか

ドキュメントの内容によりますが、以下のガイドラインが役立つかもしれません:

- プロジェクトのドキュメント（例: ユーザーガイド、APIリファレンスなど）を含める場合は、docsフォルダが適しています。
- コラボレーション関連のドキュメント（例: Issueテンプレート、貢献ガイドラインなど）は、.githubフォルダに配置します。

したがって、一般的にはdocsフォルダと.githubフォルダの両方を使い分けることが最適です。それぞれの役割に応じたドキュメントを適切なフォルダに配置することで、リポジトリの構造が整理され、共同開発者にも分かりやすくなります。

使い分けた方がいいのかな、？そうなると、このことを何かのファイルに書いておくべきなのかな

**Comment by kazzyfrog** [comment]
> .githubフォルダ: コラボレーションに関連する設定ファイル（例: Issueテンプレート、Pull Requestテンプレート、CONTRIBUTING.md、CODEOWNERSなど）を配置するためのフォルダ

現状、docsフォルダに、CONTRIBUTING.mdがあるので、
まとめた方がわかりやすいかな、と思った感じですー！👍
