### ISSUE TITLE
next/fontの設定

### ISSUE THREAD

**Issue by kagomen** [lgtm-factory/lgtm-factory#53]
## 概要
#46 #49 の完了後、使用フォントが決まっていれば、next/fontでフォントの設定をする
【追記】
とりあえずデザインカンプがまとまるまでは、InterとNotoSansJPでいきます！
その後の変更可能です！！

## 目的
サイトで表示されるカスタムフォントを設定する

## タスク

- [ ] next/fontでInterとNotoSansJPを設定する

## 参考
- https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- https://zenn.dev/hayato94087/articles/f6557abbd6d079

**Comment by soraOrange** [comment]
できるか不明だけどやってみようかな...🚵‍♀️

**Comment by kazzyfrog** [comment]
InterとNotoSansJP で一旦決まったので、
もし、他にこのイシューをやりたい方がいなければ、もらいます👍

**Comment by kagomen** [comment]
返事し忘れてました！自分は大丈夫です！！お願いします🙏🙏🌟

**Comment by kazzyfrog** [comment]
ありがとうございます👍
