### ISSUE TITLE
プルリクテンプレートのイシュー番号に `closed #` を追加する

### ISSUE THREAD

**Issue by kagomen** [lgtm-factory/lgtm-factory#59]
## 概要
プルリクテンプレートの「関連イシュー番号」の項目に `closed #` を追加する

## 目的
プルリクのマージ後、自動でイシューをクローズさせるため（現在は手動でクローズさせてます）

## 参考
- https://github.com/lgtm-factory/lgtm-factory/pull/28

**Comment by kazzyfrog** [comment]
イシュー化ありがとうございます！！🙌
