### ISSUE TITLE
イシューテンプレートの作成

### ISSUE THREAD

**Issue by kagomen** [lgtm-factory/lgtm-factory#6]
## 概要
ここ（Issuesページ）にイシューを記入するための、テンプレートを作成します！
これを導入すると、New Issueボタンをクリックしたときに、以下のように表示されるようになります。

<img width="554" alt="スクリーンショット 2024-08-05 14 14 48" src="https://github.com/user-attachments/assets/02084f55-66d1-418c-9b00-e3b631cca8b9">

どのテンプレートでイシューを作成するか選択すると、以下のようにテンプレートが表示されるので、

<img width="543" alt="スクリーンショット 2024-08-05 14 15 06" src="https://github.com/user-attachments/assets/c4f7d9ab-871f-4f2b-ab7c-ba487d63ceb3">

このテンプレートに沿って、イシューを作成する感じです！

イシューの作成方法はいくつかあるのですが（[参照](https://docs.github.com/ja/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository)）、特に希望が無ければ、自由度が高く、プルリクの練習にもなる[こちら](https://docs.github.com/ja/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#configuring-the-template-chooser)の方法を採用する方向が良いんじゃないかな？と思います
もしご意見あればお願いします！

**Comment by siso001** [comment]
issueテンプレートの参考資料
・https://qiita.com/e99h2121/items/2690103fce58cdbdc714

**Comment by siso001** [comment]
[オレオレ GitHub Issue テンプレートを晒す](https://hoto17296.hatenablog.com/entry/github_template)より
> Issue に登録するものってカテゴリに分けられるような気がして。
> すごく大雑把に分けて「要望」と「不具合」かな、と思った。
> これをひとつのテンプレートにまとめてしまうと「知りたいこと」が書ききれずにまた質問しなきゃいけなくなりそうだし、 > かといってこれ以上細かくするとテンプレートが巨大になってしまうので、これくらいがいい塩梅なんじゃないだろうか。

**Comment by siso001** [comment]
「要望」と「不具合」以外にあった方がいいな、っていうテンプレートが出てきたら後から追加すればいいのかな...？

**Comment by kagomen** [comment]
@siso001 

> 「要望」と「不具合」以外にあった方がいいな、っていうテンプレートが出てきたら後から追加すればいいのかな...？

ですね！必要があれば後から追加で良いと思います！！

**Comment by siso001** [comment]
了解です！

**Comment by siso001** [comment]
Discussionのカテゴリー名で思い出しましたが、issueテンプレートのタイトルは三文字未満だとエラーが起こるので、次回他の人が追加するかもしれないのでメモしておきます！
