### ISSUE TITLE
Cloudflare Pagesへデプロイする

### ISSUE THREAD

**Issue by kazzyfrog** [lgtm-factory/lgtm-factory#62]
## 概要
- #60 

上記にて、デプロイ先を比較・検討した末、Cloudflare Pages にデプロイする。

サービス名を変更する可能性が高そう ＆ 最悪本リリースまでにデプロイ先変えることもできるように、
開発用の環境として、仮URL（lgtm-factory.pages.dev）で、デプロイします！

なので、
- 本リリース？時に、確定したサービス名のドメインに変更する
- 開発の段階で、Cloudflare Pagesで本当に問題ないか、確認していく
 
## 目的
製品のデプロイのため、自明。

 ## 提案内容
上述した通り。

 ## タスク
 
 - [x] 参考のガイドに沿って、デプロイ

## 参考
以下の、公式のフルスタックNext.jsのデプロイガイドを参照：
https://developers.cloudflare.com/pages/framework-guides/nextjs/

**Comment by kazzyfrog** [comment]
- #63 

上記のPRがマージされたので、Cloudflare Pages のダッシュボード上から、デプロイしました！
URLは、こちら：

**Comment by kagomen** [comment]
デプロイめでたい！🚀💫
ありがとうございます！🙏
