### ISSUE TITLE
GitHubマークダウン形式の、画像のURLコピーボタンの作成

### ISSUE THREAD

**Issue by kazzyfrog** [lgtm-factory/lgtm-factory#78]
## 概要

LGTM画像を使用する際の、
GitHubマークダウン形式の、画像のURLコピーボタンを作成します。

（デザインカンプができていないので、UIは仮で、ほとんどスタイルなしでOKです！　）

## 目的

サイトでお気に入りの画像を選んだら、
ボタンをクリックしてURLをコピーし、そのままGitHub上に貼り付けて使用できるようにするため。

## タスク

- [x] （まだ作成されていなければ、ボタンコンポーネントを作成）
- [x] ボタンクリック時に呼び出される、コピー処理を行う関数の作成
- [x] サイト上に、仮でコピーボタンの設置

## 参考

- GitHub マークダウン形式: https://docs.github.com/ja/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#images
- コピー機能: https://zenn.dev/k_kazukiiiiii/articles/b6edbd13ab6b2c

開発するサービスの仕様に関しては、ざっくりこちらにまとめています
 - #74

実際の実装イメージは、kagomeさんのデモが参考になります
- Webサイト：https://satori-practice-2.vercel.app/
- ソースコード：https://github.com/kagomen/satori-practice-2

**Comment by siso001** [comment]
ボタンコンポーネントはこちらを参考にします！
https://zenn.dev/youtuber/articles/6a794bc774e6d7

**Comment by siso001** [comment]
コピー機能は @kazzyfrog さんがメモしてくれた記事https://zenn.dev/k_kazukiiiiii/articles/b6edbd13ab6b2cを参考に実装します

**Comment by kagomen** [comment]
@siso001 commitされているのですがプルリクが作成されていないので、もし忘れている場合はお願いしますー！🙏🐈‍⬛

**Comment by siso001** [comment]
忘れていました、申し訳ないです！
