### ISSUE TITLE
画像を生成するAPIエンドポイントの作成

### ISSUE THREAD

**Issue by kazzyfrog** [lgtm-factory/lgtm-factory#80]
## 概要

この機能に関しての概要は、こちらにまとめてあります。
 - #74

上記の通り、
next/ImageResponse を使用して、画像を生成し、返却するAPIエンドポイントの実装です。

URL（ディレクトリ構成）は、任せます。
`api/v1/generate-image`などが、無難でしょうか！

上記のURLで、実装が完了した場合は、
`api/v1/generate-image?thema=simple-emoji&emoji=⛑️`
にアクセスした場合、以下の画像が返却されるようになるイメージです👍
![image](https://github.com/user-attachments/assets/c4eabccb-0f38-4094-9b7f-9c9136f4715c)

上記のURLで、以下を指定しています
- ?thema=simple-emoji：画像のテーマ（種類）は、「simple-emoji」
- &emoji=⛑️：画像の中身の絵文字は、「⛑️」

## 目的

様々なデザインをもとに、動的な値（テキスト、絵文字、色、、）に応じた、画像を生成するため。
サーバーサイドの機能です。

## タスク

- [x] Next.jsの、Route Handlers を使って、URLに応じた画像を生成＆返却するAPIを作成する
    - 具体的には、Next.jsの ImageResponse という機能で、画像を生成する
    - 動的な値は、クエリパラメータによって、受け取る

**その他**：
下記は、別イシューとして切る出す予定なので、
できれば or チャレンジしたい場合は、一緒にやってしまってもOKです。

- [ ] エラーハンドリング（エラー時には、エラー用の画像返せたら良さそう。。！）
- [ ] キャッシュ設定（完全に同じURLの場合、全く同じ画像が返却させるので、キャッシュしたい！）
- [ ] URLのバリデーション（emoji=#ffffff）など、おかしな値が飛んできた際の対処

その他、色々、悩むことなどあるかと思います。
着手前でも、作業中でも、たくさんの質問を受け付けています！

自分で判断できるところは、してもらってOKです！！👍

## 参考

実際の実装イメージは、下記のデモが参考になります
- Webサイト：https://satori-practice-2.vercel.app/
- ソースコード：https://github.com/kagomen/satori-practice-2
- 複数のデザインをクエリパラメータで識別する実装デモ：https://github.com/lgtm-factory/lgtm-factory/blob/_playground/src/app/api/generate-image/route.tsx
- 画像デザインデータを別ファイルにまとめるデモ：https://github.com/lgtm-factory/lgtm-factory/tree/_playground/jsx-data

**Comment by kagomen** [comment]
こちら、立候補者がいなければ挑戦してみても良いでしょうか……！

**Comment by kazzyfrog** [comment]
@kagomen 
ぜひ👍
