### ISSUE TITLE
サービス名と表記を決める

### ISSUE THREAD

**Issue by kazzyfrog** [lgtm-factory/lgtm-factory#9]
## 概要
- サービス名（及び、リポジトリ名）は、「LGTM Factory」で良いかどうか？
- また、表記はどれで揃えるか
    - LGTM-factory
  -  LGTM-Factory
  - lgtm-factory

ぜひ、コメントを追加してください！

**Comment by siso001** [comment]
Fが大文字なのである程度統一感があって、LGTM-Factoryが個人的にはいいなと思います！

**Comment by kagomen** [comment]
参考になるかなー？と思い、色んなリポジトリ見てみました
TypeScriptが大文字使ってた！👀

<img width="264" alt="スクリーンショット 2024-08-05 16 38 53" src="https://github.com/user-attachments/assets/7685f988-0a68-4766-ac8e-033e83966e61">
<img width="199" alt="スクリーンショット 2024-08-05 16 38 41" src="https://github.com/user-attachments/assets/de44edf7-9f36-4f45-8013-70fdd22b6e6b">
<img width="225" alt="スクリーンショット 2024-08-05 16 38 25" src="https://github.com/user-attachments/assets/8a5cdddf-6ec4-4048-8a45-6a2acd940c62">
<img width="179" alt="スクリーンショット 2024-08-05 16 37 59" src="https://github.com/user-attachments/assets/1518face-791d-402b-8e64-0d4b8e92f4dd">
<img width="154" alt="スクリーンショット 2024-08-05 16 37 45" src="https://github.com/user-attachments/assets/f10eedb4-a13b-4712-8317-55eeb94cf110">
<img width="184" alt="スクリーンショット 2024-08-05 16 37 26" src="https://github.com/user-attachments/assets/424db9cd-9c24-43f0-93c3-a233835e7154">

**Comment by kazzyfrog** [comment]
以下に変更：
- サービス名が、「LGTM Factory」
- URLやリポジトリ名の表記は、小文字とハイフンでつなげた「lgtm-factory」

完了したので、閉じますー！
