### ISSUE TITLE
APIのキャッシュ設定

### ISSUE THREAD

**Issue by kagomen** [lgtm-factory/lgtm-factory#90]
## 概要
APIのキャッシュ設定（#80 からのタスクの切り分け）

## 目的
完全に同じURLの場合、全く同じ画像を返却させるのでキャッシュをしたい

## タスク

- [ ] ?

## 参考
- https://nextjs.org/docs/app/building-your-application/caching

## 追記
#135 での話し合いの結果、とりあえずキャッシュの設定は喫緊のイシューではなくなりました

- リクエスト数の制限とか、気にしないといけなくなったら
- キャッシュ周り深掘りしたくなったら

上記の際に実装できればと思いますー！

**Comment by soraOrange** [comment]
ちなみにこれ自分担当してよかったですかね...

**Comment by kagomen** [comment]
@soraOrange 

もちろんですー！👍
Next.jsの鬼門の部分かと思いますが……！❤️‍🔥
自分も時間があれば、調査を続けようと思います！

**Comment by kazzyfrog** [comment]
ディスカッションの結果、一旦着手しそうにないので、計画外としてクローズしますね🙌
