### ISSUE TITLE
クエリパラメーターのバリデーションを実装

### ISSUE THREAD

**Issue by kagomen** [lgtm-factory/lgtm-factory#91]
## 概要
クエリパラメーターのバリデーション（#80 からのタスクの切り分け）
#109 が完了したら、取り組むことができそう！

## 目的
指定したクエリにおかしな値が飛んできた際の対処

## タスク

- [ ] zodを使う？

## 備考
どんなクエリパラメーターが必要か、がある程度決まってから着手する感じで良いかな？と思い、`Priority: Low`のラベルを設定しました🐢

**Comment by risu043** [comment]
私もやってみたいです

**Comment by kagomen** [comment]
@risu043 
ぜひぜひ！お願いします！🙏🌟
ブランチやコミットの命名規則は以下を参照してくださいー！
https://github.com/lgtm-factory/lgtm-factory/blob/main/.github/CONTRIBUTING.md

イシューに取り組む際はイシュー右サイドのassign-yourselfにて、ご自身をアサインしてから作業の開始をお願いします！
<img width="134" alt="スクリーンショット 2024-08-23 21 25 58" src="https://github.com/user-attachments/assets/ffba695a-c87e-4476-aa0d-793a577716d7">


また、できればDiscussionsのScrapで調査報告をしながら実装していただけると、レビュワーが大変助かりますー！🙇🌈
