### ISSUE TITLE
エラー時に返される画像を良い感じにする

### ISSUE THREAD

**Issue by kagomen** [lgtm-factory/lgtm-factory#92]
## 概要
現在設定されているのが簡素なものなので、これをもっと良い感じにする！
現在の画像:
<img width="682" alt="スクリーンショット 2024-08-22 19 12 45" src="https://github.com/user-attachments/assets/9d9f3cb4-5974-46c1-bf55-279e2cee725b">

## タスク

- [ ] lgtm-data/error.tsx のCSS(Tailwind)の値をいじって、良い感じにする🐈‍⬛
- [ ] #95 からのメッセージを受け取って、表示させる

**Comment by kazzyfrog** [comment]
これでよければ！コーディングに着手します！
![Group 150](https://github.com/user-attachments/assets/456dc28f-5a31-4da8-84e4-697d60c04517)

**Comment by kagomen** [comment]
良いと思います！かわいい😻👀🌈
